### ISSUE TITLE
sacad_r on Windows not giving any output or doing anything

### ISSUE THREAD

**Issue by ransagy** [desbma/sacad#13] opened 2017-10-31 23:28 UTC
I've had this for a while now. I keep trying to use sacad_r every new release, but in my case (Windows 10 Pro x64) sacad_r never gives me any output, not even the running the exe without any arguments or with the -h argument. It also does not seem to do anything, even if i use the example arguments for it as in the main readme.

Anything else i can try to provide more info on this?

**Comment by beingalink** [comment] 2017-11-01 10:11
Same for me. Also on Win 10 Pro.

**Comment by desbma** [comment] 2017-11-01 14:03
Thanks for the report, it should be fixed in version 2.0.3 which will be published automatically in a few minutes.

Please don't hesitate to report any other problem you encounter in the future. All my systems are on Linux, so I do not test much on Windows and might miss some Windows specific issues.

**Comment by desbma** [comment] 2017-11-01 14:50
I found another weird Windows issue that causes a freeze of `sacad_r` on some machines only, so until that is fixed too, release of version 2.0.3 might be delayed.

**Comment by ransagy** [comment] 2017-11-01 14:57
I'll keep watching this and test ASAP then. Thanks!

**Comment by desbma** [comment] 2017-11-02 00:01
[Version 2.0.4](https://github.com/desbma/sacad/releases/tag/2.0.4) has been released which should fix `sacad_r` Windows issues.

Please test and confirm all is working well.

**Comment by beingalink** [comment] 2017-11-02 06:09
sacad_r runs now with 2.0.4 but I get following error on my library;
```
Searching covers:   0%|                                | 0/384 [00:00<?, ? covers/s, errors=0, no result found=0, ok=0]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "sacad\recurse.py", line 298, in <module>
  File "sacad\recurse.py", line 294, in cl_main
  File "sacad\recurse.py", line 250, in get_covers
  File "C:\Python34\lib\asyncio\base_events.py", line 325, in run_until_complete
  File "C:\Python34\lib\asyncio\base_events.py", line 295, in run_forever
  File "C:\Python34\lib\asyncio\base_events.py", line 1218, in _run_once
  File "C:\Python34\lib\selectors.py", line 314, in select
  File "C:\Python34\lib\selectors.py", line 305, in _select
ValueError: too many file descriptors in select()
```

**Comment by desbma** [comment] 2017-11-02 08:31
Thanks  @beingalink 
Can you tell me approximately how many files and directories you have in your library?

@ransagy can you please test [version 2.0.4](https://github.com/desbma/sacad/releases/tag/2.0.4) and check if you have the same issue?

**Comment by ransagy** [comment] 2017-11-02 09:31
This is what i got with 2.0.4 -
```
PS E:\Software\Sacad> .\sacad_r.exe E:\Music\ 600 Test.jpg
Analyzing library: 257 dirs [00:01, 171.61 dirs/s, files=2.83e+03, albums=180, missing covers=180, errors=0]
Searching covers: 100%|##############################| 180/180 [02:03<00:00,  3.70s/ covers, ok=44, errors=0, no result found=136]`
```
.. followed by the expected lines of 'unable to find cover for X'.

**Comment by beingalink** [comment] 2017-11-02 17:38
@desbma 674 directories and 5620 files

**Comment by desbma** [comment] 2017-11-02 22:15
@ransagy The initial issue you reported is fixed then. You have a very high number of 'not found' covers though. This might be due to files with missing or incorrect tags.

@beingalink I have found the cause of this issue. It's due to a known Python limitation on Windows only. I have found a way to fix this, but only on Python > 3.5, and the Windows executable are generated with Python 3.4. I need some time to think about the best way to fix this.
In the mean time, you can run `sacad_r` on smaller directory trees by running it on earch subdirectory of your library and it should work.

**Comment by desbma** [comment] 2017-11-05 13:15
@beingalink Can you please try [version 2.0.5](https://github.com/desbma/sacad/releases/tag/2.0.5) in the same conditions that previously caused the error, and tell me if it is fixed?

**Comment by desbma** [comment] 2017-11-14 08:16
No news is good news, I consider this is fixed then.

If you encounter any problem, please open a new issue.

**Closed by desbma** 2017-11-14 08:16 UTC

**Comment by jonlanghoff** [comment] 2018-08-01 19:58
Hi :)
I'm getting this:

Searching covers:   0%|                                                                                                                                                                            | 1/2929 [00:01<1:12:20,  1.48s/ covers, ok=0, errors=1, no result found=0]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "sacad\recurse.py", line 320, in <module>
  File "sacad\recurse.py", line 316, in cl_main
  File "sacad\recurse.py", line 267, in get_covers
  File "C:\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
  File "sacad\recurse.py", line 210, in update_progress
  File "Z:\data\Projets\Sacad\sacad\__init__.py", line 46, in search_and_download
  File "Z:\data\Projets\Sacad\sacad\sources\base.py", line 92, in search
  File "Z:\data\Projets\Sacad\sacad\cover.py", line 306, in updateImageMetadata
  File "Z:\data\Projets\Sacad\sacad\cover.py", line 322, in setSizeMetadata
AssertionError

I ran the script like this - sacad_r D:\iTunes 500 AlbumArt.jpg - and it got 11% through my library and then it crashed with the above message. When trying to rerun the script with -i added, it makes the same error, but immediately, so I'm thinking that it has met something at a certain place in my library that it dislikes..?

Cheers,
Jon :)

**Comment by desbma** [comment] 2018-08-02 10:54
@jonlanghoff 
You have commented on an unrelated issue.
I have opened a new one for you [here](https://github.com/desbma/sacad/issues/20), please go to the new issue to continue discussion.
