### ISSUE TITLE
I can't choose cover for exact track

### ISSUE THREAD

**Issue by kogeke** [desbma/sacad#93] opened 2023-10-16 15:41 UTC
Track named "You", but sacad always download art for track "you should know", there is no option to choose what art to download.

**Comment by desbma** [comment] 2023-10-16 19:04
sacad by design is non interactive, so that you can use it in scripts or from other programs to automatically download covers.

However if you can give me the exact arguments you are passing to sacad, the result that is download, and the result that is available and you would like to be downloaded instead, maybe I can look at it and improve the cover choice.

**Comment by kogeke** [comment] 2023-10-16 19:30
i type: sacad "Vin Jay" "You" 600 AlbumArt.jpg

i expect https://music.apple.com/us/song/you/1651073602

i get https://music.apple.com/za/album/you-should-know-single/1581061598

**Comment by desbma** [comment] 2023-10-30 12:49
It should be now fixed by d781fb1.

**Closed by desbma** 2023-10-30 12:49 UTC

**Comment by kogeke** [comment] 2023-10-30 18:14
Thanks!
