### ISSUE TITLE
Match image with the largest resolution from reliable sources

### ISSUE THREAD

**Issue by baoshan** [desbma/sacad#7] opened 2016-02-19 03:26 UTC
#6 deals mainly with the improvement over resizing. There're 4 album referenced in that issue. I made a comparison between the current `sacad` behavior when used on a `540px` device, with using the largest possible version. The `Pictures` album is excluded for that's unfair for `last.fm` (only `300px` version provided).

Current Behaviour:

+ resolution is a required argument;
+ favor `png` over `jpg` for same resolution;
+ default tolerance (25%)

Proposed Behaviour:

+ no resolution argument required;
+ favor highest resolution image from reliable sources;
+ No resizing (unless asked)

This test resizes all images to `540px` using `ImageMagick` command `convert A.png -resize 540x540 -quality 100 A.540.png` (which simulate what the users see actually, according to the use case you proposed). If you feel the `540px` is unfair for some `last.fm` images are `500x500` (the mega one), I'm glad to post a `480px` version.

No | Current Behaviour | Proposed Behaviour
------------ | ------------ | -------------
1 | ![a 540](https://cloud.githubusercontent.com/assets/1096182/13165578/c29542c6-d6f9-11e5-9f2a-381f2904b4ad.png) | ![a 540](https://cloud.githubusercontent.com/assets/1096182/13165586/d0d9d284-d6f9-11e5-994b-170c92726555.png)
2 | ![b 540](https://cloud.githubusercontent.com/assets/1096182/13165590/e0746e52-d6f9-11e5-87d5-e0912929b621.png) | ![b 540](https://cloud.githubusercontent.com/assets/1096182/13165596/eb4efc02-d6f9-11e5-8836-b7e7d427e1c1.png)
3 | ![c 540](https://cloud.githubusercontent.com/assets/1096182/13165606/f7f7c65a-d6f9-11e5-90b1-03d2c3f6b9e9.png) | ![c 540](https://cloud.githubusercontent.com/assets/1096182/13165622/10de215a-d6fa-11e5-832d-f50adfcc4552.png)
Size | 1,054,095 Bytes | 794,931 Bytes
Optimised Size | 908,128 Bytes | 794,931 Bytes
Time used to decode | 172 ms | 382 ms 

The size is based on the un-resized version; the time is calculated using `convert A.jpg -resize 540x540 A.540.bmp` and `convert A.png -resize 540x540 A.540.bmp` respectively.

The proposal:

1. shows a storage efficiency (+14% ~ +33%);
2. shows a less time efficiency (-123%);
3. with a clear improvement on image quality, see the text on test 2 and adele's nose and lips on test 3, and all 3 tests reveals a more layered colour depth, although this is subjective, I'd like to post some camera shots with calibrated screen if necessary;
4. You inevitable upgrade your device, but not your collection, if a tablet uses `960px` to show the image, the proposed policy is definitely an all winner, while the users using the current `sacad` have to re-match again.

Thanks and I'd like to hear your thoughts.

**Comment by desbma** [comment] 2016-02-19 12:26
It's not clear to me what you are trying to demonstrate with the images, and also how you generated the images/data: how did you generate the images in _Current Behaviour_/_Proposed Behaviour_ column? from what did you resize? if image comes from SACAD before resize, what SACAD command did you use? what does _Optimised Size_ means, how did you measure _Time used to decode_?
If you have written a script or similar, please post it here that'll be easier to understand and reproduce.

Also please post thumbnails with link to full size images, it's easier to read than full images in message.

And most importantly, **before discussing any "proposal", what is wrong with the current behavior?** 
In the previous issue you showed me a clear example with a command where the result had visible artifacts after resize, can you please do something similar for this issue?

**Comment by baoshan** [comment] 2016-02-19 12:44
I think the title does explain my proposal clearly.

+ The current behaviour is generated using `sacad "adele" "25" 600 current.png`
+ the proposed behaviour is generated using the largest resolution available.

From there, both images are resized to 540px since your reference scenario uses a `540px by 960px` smartphone.

The size of current behaviour is the sum of 3 `png` of size `600x600`; the size of the proposed behaviour is the sum of 3 `jpg` of size `1500x1500`.

We're talking about making the users' collection future proof, so use largest resolution is my proposal.

**Comment by baoshan** [comment] 2016-02-19 12:47
The current SACAD is not (at least, automatically) future proof, that's not wrong, but can be improved.

**Comment by desbma** [comment] 2016-02-19 18:43
>  I think the title does explain my proposal clearly.

And you want to discuss a solution without having stated what the problem is.

If you want to download a high resolution cover or avoid resizing you can do so with the current command line parameters.
Unless you are more more specific about what your use case is, that SACAD does not currently satisfy, this discussion will go nowhere.

**Comment by baoshan** [comment] 2016-02-20 01:48
Let's try to be more specific on the problem:

Suppose you're using a `540 by 960` device and match all your collection using `sacad "artist" "album" 600 600.jpg`. Then:

1. Covers shown on the device are not of the best quality we can make (which I showed at the beginning of the thread);
2. When you upgrade your device, maybe a tablet with doubled resolution, you have to match (using `sacad "artist" "album" 1200 1200.jpg`) again to get crisp image.

That's the problem, can you see it this time?

**Comment by baoshan** [comment] 2016-02-20 01:54
> If you want to download a high resolution cover or avoid resizing you can do so with the current command line parameters.

I don't think so. `sacad -t 50 "artist" "album" 1600 1600.jpg` will still resize the image if the source is `3200 by 3200`. Current design can not get me the highest resolution image, untouched.

You use the same tolerance for both matching and resizing, which is the origin of that.

**Comment by desbma** [comment] 2016-02-20 12:07
>  I don't think so. sacad -t 50 "artist" "album" 1600 1600.jpg will still resize the image if the source is 3200 by 3200. 

Have you ever found a cover of that size? 
That should never happen in practice, and if it does it is either an unrelated image coming from a low reliability source like Google Images, or a cover scanned by someone clueless that set a very high DPI without realizing that the added pixel are just interpolated.

**Comment by baoshan** [comment] 2016-02-20 12:42
> That should never happen in practice.

Agreed.

Can you see the two possible problem I described above? And, can you help me understand why the following command only generate a `500px` image while there're available `1500px` one?

`sacad -t 75 "Alice Sara Ott" "Pictures" 1500 pictures.jpg`

Thanks again.

**Comment by desbma** [comment] 2016-02-20 17:20
>  Can you see the two possible problem I described above?

If you want to target 540px and absolutely avoid a resize at display time, pass `540 -t 0`.
When you ask sacad to download a cover at size X, you get size X, but's it's not "future proof", because maybe in the future you'll want size Y?

This does not make any sense to me.

**Please let's keep this only about specific issues, not about feature ideas or change proposals.**

>  And, can you help me understand why the following command only generate a `500px` image while there're available `1500px` one?

> `sacad -t 75 "Alice Sara Ott" "Pictures" 1500 pictures.jpg`

It looks unexpected indeed, I'll look at it.

**Comment by desbma** [comment] 2016-02-20 20:27
The `sacad -t 75 "Alice Sara Ott" "Pictures" 1500 pictures.jpg` case is now fixed.

The correction will be available in the next version (1.6.6).

**Closed by desbma** 2016-02-20 20:27 UTC

**Comment by baoshan** [comment] 2016-02-21 01:22
Thanks very much for the fix.

> If you want to target 540px and absolutely avoid a resize at display time, pass 540 -t 0.
When you ask sacad to download a cover at size X, you get size X, but's it's not "future proof", because maybe in the future you'll want size Y?

No. It's not me who want to pass in the `540` params. __It's SACAD who forces users to enter a magic number which does not make any sense due to the speed (and possible forms) of new devices.__

Think of _content oriented responsive design_ vs _device oriented responsive design_.This is a textbook example we should avoid using specific device's resolution when preparing your master assets.

I suggest everyone (yes, I couldn't find an exception) to download covers using:

`sacad -t 100 artist album 1600 cover.jpg`

**Comment by baoshan** [comment] 2016-02-21 02:06
Could you inspect why the following command output a thumbnail of `300x300` after install from the source?

`sacad -t 85 "Alice Sara Ott" "Pictures" 1500 cover.jpg`

Thanks.

**Comment by desbma** [comment] 2016-02-21 12:04
Thanks for the new example. It is also fixed in https://github.com/desbma/sacad/commit/7aca6a9a6a5d23f0dd8d295553425af271bf0b97.
I have removed the _"Prefer covers of "reference" source quality"_ sorting factor because it was redundant with _"Prefer covers of reliable source"_ and was taking precedence over _"Prefer size above target size"_.

**Comment by baoshan** [comment] 2016-02-21 12:05
Thanks and I'll close the PR then.
