### ISSUE TITLE
Incorrect images

### ISSUE THREAD

**Issue by maszaa** [desbma/sacad#40] opened 2020-05-21 09:17 UTC
Sacad keeps downloading incorrect images. I think matching to artist and album name should be improved. Couple of examples:

Mikko Kuustonen: Aurora
- Should look like this: https://img.discogs.com/KZa1akG9fh_ZgmH4NYC1g9kBUmc=/fit-in/600x597/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2979788-1310211997.jpeg.jpg
- This is what sacad gives
```
sacad "mikko kuustonen" "aurora" --size-tolerance 33 --amazon-sites fr de co.uk ca -- 1500 Folder.jpg
Main: jpegoptim could not be found, JPEG crunching will be disabled
Main: optipng could not be found, PNG crunching will be disabled
LastFmCoverSource: Got 0 relevant (5 excluded) results from source 'LastFmCoverSource'
AmazonDigitalCoverSource: Got 7 relevant (4 excluded) results from source 'AmazonDigitalCoverSource'
AmazonCdCoverSource: Got 0 relevant (0 excluded) results from source 'AmazonCdCoverSource'
AmazonCdCoverSource: Got 0 relevant (0 excluded) results from source 'AmazonCdCoverSource'
AmazonCdCoverSource: Got 0 relevant (0 excluded) results from source 'AmazonCdCoverSource'
AmazonCdCoverSource: Got 0 relevant (0 excluded) results from source 'AmazonCdCoverSource'
GoogleImagesWebScrapeCoverSource: Got 0 relevant (0 excluded) results from source 'GoogleImagesWebScrapeCoverSource'
AmazonCdCoverSource: Got 0 relevant (0 excluded) results from source 'AmazonCdCoverSource'
Cover: Reference is: LastFmCoverSourceResult 'https://lastfm.freetls.fastly.net/i/u/300x300/838dd45156a647e8a484b74bfda5d98a.png'
Cover: Downloading cover 'https://m.media-amazon.com/images/I/817hhdGaCgL.jpg' (part 1/1)...
Cover: Resizing from 2000x2000 to 1500x1500...
```
Why does it use Last.fm cover as reference though it got 0 relevant images?

Mikko Kuustonen: Abrakadabra
```
sacad "mikko kuustonen" "abrakadabra" --size-tolerance 33 -- 1000 Folder.jpg
Main: jpegoptim could not be found, JPEG crunching will be disabled
Main: optipng could not be found, PNG crunching will be disabled
AmazonCdCoverSource: Got 1 relevant (0 excluded) results from source 'AmazonCdCoverSource'
LastFmCoverSource: Got 0 relevant (5 excluded) results from source 'LastFmCoverSource'
AmazonDigitalCoverSource: Got 2 relevant (0 excluded) results from source 'AmazonDigitalCoverSource'
GoogleImagesWebScrapeCoverSource: Got 0 relevant (0 excluded) results from source 'GoogleImagesWebScrapeCoverSource'
Cover: Reference is: LastFmCoverSourceResult 'https://lastfm.freetls.fastly.net/i/u/300x300/4d857b1b11d648d7b39b57f08e0a70db.png'
Cover: Downloading cover 'https://m.media-amazon.com/images/I/81bvWh0JgNL.jpg' (part 1/1)...
Cover: Resizing from 1400x1388 to 1000x1000...
```
The reference image from Last.fm is correct but the downloaded image is not.

Atomirotta: II
```
sacad "atomirotta" "II" --size-tolerance 33 -- 1500 Folder.jpg
Main: jpegoptim could not be found, JPEG crunching will be disabled
Main: optipng could not be found, PNG crunching will be disabled
AmazonCdCoverSource: Got 0 relevant (0 excluded) results from source 'AmazonCdCoverSource'
GoogleImagesWebScrapeCoverSource: Got 0 relevant (0 excluded) results from source 'GoogleImagesWebScrapeCoverSource'
LastFmCoverSource: Got 0 relevant (5 excluded) results from source 'LastFmCoverSource'
AmazonDigitalCoverSource: Got 11 relevant (5 excluded) results from source 'AmazonDigitalCoverSource'
Cover: Reference is: LastFmCoverSourceResult 'https://lastfm.freetls.fastly.net/i/u/300x300/6bee182e7bbf234fe12f58e1fca5fe48.png'
Cover: Downloading cover 'https://m.media-amazon.com/images/I/81a-Gur8k5L.jpg' (part 1/1)...
Cover: Resizing from 2560x2560 to 1500x1500...
```
Once again the reference is correct but the downloaded image isn't even a CD or album front cover, something completely different...

I would rather get notified that a cover with given size scale wasn't found than get my library populated with incorrect images.

**Comment by desbma** [comment] 2020-05-21 10:41
> Why does it use Last.fm cover as reference though it got 0 relevant images?

You have asked for a very high image size, so that exludes all LastFM results. However because LastFM is a very reliable source, Sacad will look for results that looks like that reference. 

> The reference image from Last.fm is correct but the downloaded image is not.

Increase the size tolerance (ie. with `--size-tolerance 80`), and you will get a correct (but smaller) result image.

**Comment by maszaa** [comment] 2020-05-21 11:29
> Increase the size tolerance (ie. with `--size-tolerance 80`), and you will get a correct (but smaller) result image.

I see. But I would still like sacad to report that there wasn't good enough match rather than download an image matching the size tolerance but differing completely in content. Maybe a strict mode with `-s/--strict` that would do enable it? And without it sacad would operate as it does now.

**Comment by desbma** [comment] 2020-05-21 12:16
The thing is, this is not always a binary choice (good/crap cover).

Sometimes a cover that does not look like the reference can be a correct one (because there is a sticker on the image, or because it is an alternate cover). The [algorithm](https://github.com/desbma/sacad/blob/11f50d82fe7fc0ef96481982b04036231a3da11d/sacad/cover.py#L364-L383) works by comparing covers two by two by looking at many factors, which sorts the results, and then try to download them in order.

Originally I have added `--disable-low-quality-sources` exactly for your need: when you prefer the program to fail than to risk downloading a laxative image :wink: . However only Google Image is classified as "low quality" and disabled by that option. Amazon can be a great source for high quality images, but now you can get quickly blocked when doing a few searches, and sometimes you get non cover images.

I believe the root cause is the lack of high quality cover sources. coverlib.com was really an amazing source of >1000px covers, but it was shut down a few years ago. https://albumartexchange.com/ is also good, but they are very aggressively blocking automated scraping, so it can not be used by Sacad.

**Comment by maszaa** [comment] 2020-05-21 12:47
How about Deezer? They have some good cover images.
For these three albums:
https://api.deezer.com/search?q=artist:"Mikko Kuustonen" album:"Aurora"
https://api.deezer.com/search?q=artist:"Mikko Kuustonen" album:"Abrakadabra"
https://api.deezer.com/search?q=artist:"Atomirotta" album:"II"
I'm able to find a correct cover.

I would even be interested for implementing that as a cover source. Just need to first check the limitations etc.

**Comment by desbma** [comment] 2020-05-21 15:36
The Deezer API looks good, I'll implement something quickly.

**Comment by desbma** [comment] 2020-05-21 16:31
New Deezer source: https://github.com/desbma/sacad/commit/46f2f0101c82ad6c14941c50d9b004d8bc02c0f5

Please test and report issues !

**Comment by maszaa** [comment] 2020-05-21 17:41
Works well at least for these three albums.

**Comment by desbma** [comment] 2020-05-21 22:28
Great, I'm closing this then.

**Closed by desbma** 2020-05-21 22:28 UTC
