### ISSUE TITLE
TypeError--init--()

### ISSUE THREAD

**Issue by CrazyWolf13** [desbma/sacad#83] opened 2022-11-25 17:41 UTC
![image](https://user-images.githubusercontent.com/96661824/204034607-1f29da1d-27e9-4d3d-9914-072069a97405.png)

What am i doing wrong?
Or is this a Bug?

**Comment by CrazyWolf13** [comment] 2022-11-25 17:44
@desbma

**Comment by desbma** [comment] 2022-11-25 19:03
Duplicate of #82

**Closed by desbma** 2022-11-25 19:03 UTC

**Comment by CrazyWolf13** [comment] 2022-11-25 21:31
> 

I downloaded the latest release 4 hours ago so its not fixed :/

**Comment by desbma** [comment] 2022-11-25 21:34
I released the fix less than 2 hours ago.
